services:
  doodlebattle-db:
    image: postgres:14.10
    environment:
      POSTGRES_DB: doodle_battle
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 94justchat
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    ports:
      - "3000:3000"
    command: ["pnpm", "dev"]
    develop:
      watch:
        - action: sync
          path: ./app/client
          target: /prod/client
          ignore:
            - /node_modules
            - /dist
            - /.git

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgres://postgres:94justchat@doodlebattle-db:5432/doodle_battle"
    depends_on:
      - doodlebattle-db
    command: ["pnpm", "dev"]
    develop:
      watch:
        - action: sync
          path: ./app/server
          target: /prod/server
          ignore:
            - /node_modules
            - /dist
            - /.git

volumes:
  postgres-data:
