import { GoogleAuthProvider, signInWithPopup, signOut } from "firebase/auth";
import Head from "next/head";
import { Button } from "~/components/ui/button";
import { auth } from "~/lib/firebase";

export default function Home() {
  const googleLogin = async (): Promise<void> => {
    const provider = new GoogleAuthProvider();
    const res = await signInWithPopup(auth, provider);
    const { user } = res;
    console.log(user);
    // make a post request to http:localhost:400/api/testing-firebase
    await fetch("http://localhost:4000/api/testing-firebase", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(user),
    });

    // await res2.json();
  };
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid h-screen place-content-center gap-5">
        <Button onClick={googleLogin}>Login in With Google</Button>
        <Button
          variant={"destructive"}
          onClick={() => async () => await signOut(auth)}
        >
          Log Out
        </Button>
      </div>
    </>
  );
}
